### ISSUE TITLE
Upgrade images

### ISSUE THREAD

**Issue by DickChesterwood** [DickChesterwood/fleetman-webapp#3]
Image is at virtualpairprogrammers/fleetman-webapp
The idiot trainer of the course is using the :latest tag, which is extremely dim of him BUT it could be a saviour here!

**Comment by RichardKnowles** [comment]
There's currently only one Tag at dockerhub for this image, 
0.0.1-SNAPSHOT

I will upload a new tag, "2020-upgrade". 

Then we will need to proceed with the videos to check all is well.

**Comment by DickChesterwood** [comment]
Done.

**Comment by DickChesterwood** [comment]
Reopening as there is a fleetman-production parallel image.

**Comment by DickChesterwood** [comment]
In lecture 39 he builds fleetman-production locally. I assume that we need this on docker-hub as it will be used from play-with-docker later on.

Argh!

**Comment by DickChesterwood** [comment]
We will need the following errata before lecture 39:

You need to add the following line to the application-docker-demo.properties file:

spring.datasource.driver-class-name=com.mysql.jdbc.Driver

**Comment by DickChesterwood** [comment]
I've pushed the new fleetman-production to :latest.

We need to work out what the :no-netflix and :microservice versions are.

I believe this was for the end of the vpp course where I got rid of most of netflix. I recall this was ripped out of the udemy version.

**Comment by DickChesterwood** [comment]
Ok, I've confirmed that the new fleetman-production works ok in the play-with-docker chapter (to my amazement!).

The pick up point is to run through the microservices on ec2 chapter. This seems to use those netflix images. Urgh.

**Comment by DickChesterwood** [comment]
Resources are attached to 71 and 73.

**Comment by DickChesterwood** [comment]
Ok, it's the "docker-only-fleetman" project, and we need to upgrade this for Spring Boot 2 really.

**Comment by DickChesterwood** [comment]
The compose file points to the "no-netflix" tags.

I think we will just upgrade the webapp to not use MapBox. The rest we can leave as-is. Anyone getting this far can surely upgrade the projects for Java 9+ themselves.

**Comment by DickChesterwood** [comment]
Done.
